/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kingdom.ui;

import java.awt.CardLayout;
import kingdom.config.StartWizardConfig;

/**
 *
 * @author andriy
 */
public class StartWizard extends javax.swing.JDialog {
    
    private final StartWizardConfig wizConfig = new StartWizardConfig();

    /**
     * Creates new form StartWizard
     */
    public StartWizard(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        updatePage1(wizConfig);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnFinish = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        lblTopInfo = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        wizPage1 = new javax.swing.JPanel();
        cmbUsers = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        chkLoadGame = new javax.swing.JCheckBox();
        chkUserNum = new javax.swing.JCheckBox();
        wizPage2 = new javax.swing.JPanel();
        lblUser1 = new javax.swing.JLabel();
        lblUser2 = new javax.swing.JLabel();
        lblUser3 = new javax.swing.JLabel();
        lblUser4 = new javax.swing.JLabel();
        edtUser1 = new javax.swing.JTextField();
        edtUser2 = new javax.swing.JTextField();
        edtUser3 = new javax.swing.JTextField();
        edtUser4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Start configuration");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnBack.setText("Back");
        btnBack.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack);

        btnNext.setText("Next");
        btnNext.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        jPanel2.add(btnNext);

        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        jPanel2.add(btnFinish);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setPreferredSize(new java.awt.Dimension(865, 50));

        lblTopInfo.setText("Select optoin to start game");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopInfo)
                .addContainerGap(407, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopInfo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.NORTH);

        cardPanel.setBackground(new java.awt.Color(226, 192, 222));
        cardPanel.setLayout(new java.awt.CardLayout());

        wizPage1.setBackground(new java.awt.Color(161, 185, 223));
        wizPage1.setPreferredSize(new java.awt.Dimension(437, 437));
        wizPage1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                wizPage1ComponentShown(evt);
            }
        });

        cmbUsers.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        cmbUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUsersActionPerformed(evt);
            }
        });

        jLabel6.setText("players");

        chkLoadGame.setText("Load last saved Game");
        chkLoadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLoadGameActionPerformed(evt);
            }
        });

        chkUserNum.setSelected(true);
        chkUserNum.setText("Start new game with ");
        chkUserNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUserNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout wizPage1Layout = new javax.swing.GroupLayout(wizPage1);
        wizPage1.setLayout(wizPage1Layout);
        wizPage1Layout.setHorizontalGroup(
            wizPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizPage1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addGroup(wizPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkLoadGame)
                    .addGroup(wizPage1Layout.createSequentialGroup()
                        .addComponent(chkUserNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        wizPage1Layout.setVerticalGroup(
            wizPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizPage1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(chkLoadGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(wizPage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(chkUserNum))
                .addGap(148, 148, 148))
        );

        cardPanel.add(wizPage1, "card2");

        wizPage2.setBackground(new java.awt.Color(210, 240, 169));
        wizPage2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                wizPage2ComponentShown(evt);
            }
        });

        lblUser1.setText("User1 Name:");

        lblUser2.setText("User2 Name:");

        lblUser3.setText("User3 Name:");

        lblUser4.setText("User4 Name:");

        javax.swing.GroupLayout wizPage2Layout = new javax.swing.GroupLayout(wizPage2);
        wizPage2.setLayout(wizPage2Layout);
        wizPage2Layout.setHorizontalGroup(
            wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizPage2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser1)
                    .addComponent(lblUser2)
                    .addComponent(lblUser3)
                    .addComponent(lblUser4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtUser4, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        wizPage2Layout.setVerticalGroup(
            wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wizPage2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser1)
                    .addComponent(edtUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser2)
                    .addComponent(edtUser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser3)
                    .addComponent(edtUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(wizPage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser4)
                    .addComponent(edtUser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        cardPanel.add(wizPage2, "card3");

        getContentPane().add(cardPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        lblTopInfo.setText("Hello success");
        CardLayout cardsLayout = (CardLayout)cardPanel.getLayout();
        cardsLayout.show(cardPanel, "card3");
        //this.remove(jPanel1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         lblTopInfo.setText("Hello success111");
        CardLayout cardsLayout = (CardLayout)cardPanel.getLayout();
        cardsLayout.show(cardPanel, "card2");
    }//GEN-LAST:event_btnBackActionPerformed

    private void wizPage1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_wizPage1ComponentShown
        // TODO add your handling code here:
        updatePage1(wizConfig);
    }//GEN-LAST:event_wizPage1ComponentShown

    private void wizPage2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_wizPage2ComponentShown
        // TODO add your handling code here:
        updatePage2(wizConfig);
    }//GEN-LAST:event_wizPage2ComponentShown

    private void chkLoadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLoadGameActionPerformed
        // TODO add your handling code here:
         wizConfig.setLoadSelected(chkLoadGame.isSelected());
         updatePage1(wizConfig);
    }//GEN-LAST:event_chkLoadGameActionPerformed

    private void chkUserNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUserNumActionPerformed
        // TODO add your handling code here:
        wizConfig.setLoadSelected(false);
        updatePage1(wizConfig);
    }//GEN-LAST:event_chkUserNumActionPerformed

    private void cmbUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsersActionPerformed
        // TODO add your handling code here:
        wizConfig.setSelectedNumberOfUser(cmbUsers.getSelectedIndex() + 2); // combobox selection starts with 2
        updatePage1(wizConfig);
    }//GEN-LAST:event_cmbUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartWizard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartWizard dialog = new StartWizard(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JToggleButton btnFinish;
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JCheckBox chkLoadGame;
    private javax.swing.JCheckBox chkUserNum;
    private javax.swing.JComboBox cmbUsers;
    private javax.swing.JTextField edtUser1;
    private javax.swing.JTextField edtUser2;
    private javax.swing.JTextField edtUser3;
    private javax.swing.JTextField edtUser4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTopInfo;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JLabel lblUser2;
    private javax.swing.JLabel lblUser3;
    private javax.swing.JLabel lblUser4;
    private javax.swing.JPanel wizPage1;
    private javax.swing.JPanel wizPage2;
    // End of variables declaration//GEN-END:variables

    private void updatePage1(StartWizardConfig wizConfig) {
         chkUserNum.setSelected(!wizConfig.isLoadSelected());
         chkLoadGame.setSelected(wizConfig.isLoadSelected());
         cmbUsers.setEnabled(!wizConfig.isLoadSelected());
         
         int comboIndex =wizConfig.getSelectedNumberOfUser() - 2; // first option is 2 user
         
         if(cmbUsers.getSelectedIndex() != comboIndex){
             cmbUsers.setSelectedIndex(comboIndex);
         }
         
    }

    private void updatePage2(StartWizardConfig wizConfig) {
        if(wizConfig.isLoadSelected()){
            this.dispose();
        } else {
            int numberOfUser = wizConfig.getSelectedNumberOfUser();
            
            lblUser3.setVisible(numberOfUser > 2);
            edtUser3.setVisible(numberOfUser > 2);
            lblUser4.setVisible(numberOfUser > 3);
            edtUser4.setVisible(numberOfUser > 3);
        }
        
        lblTopInfo.setText("Provide name for all users" );
    }
}
